/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CetakData;

import DB.Koneksi;
import com.sun.glass.events.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Agung
 */
public class CetakUI extends javax.swing.JFrame {
     Statement stt;
    /**
     * Creates new form CetakUI
     */
    public CetakUI() {
        initComponents();
        tampil_combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cetakBtn = new javax.swing.JButton();
        noPacking = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        box1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cetak2Btn = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("CETAK DATA TEMPLATE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 11, 293, -1));

        cetakBtn.setBackground(new java.awt.Color(0, 0, 204));
        cetakBtn.setForeground(new java.awt.Color(255, 255, 255));
        cetakBtn.setText("Water");
        cetakBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cetakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cetakBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        noPacking.setBackground(new java.awt.Color(255, 255, 102));
        noPacking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPackingActionPerformed(evt);
            }
        });
        noPacking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noPackingKeyTyped(evt);
            }
        });
        jPanel1.add(noPacking, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 100, 61, -1));

        jLabel2.setText("Pages Ke");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 102));
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Lihat Data");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        box1.setBackground(new java.awt.Color(255, 255, 102));
        box1.setForeground(new java.awt.Color(102, 102, 102));
        box1.setToolTipText("");
        box1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        box1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                box1ItemStateChanged(evt);
            }
        });
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });
        jPanel1.add(box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 100, 223, -1));

        jLabel4.setText("Type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 80, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ic/aristek-highpolymer-pt.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 190));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ic/Button_12-128.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 80, 30));

        cetak2Btn.setBackground(new java.awt.Color(0, 204, 0));
        cetak2Btn.setForeground(new java.awt.Color(255, 255, 255));
        cetak2Btn.setText("Solvent");
        cetak2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cetak2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetak2BtnActionPerformed(evt);
            }
        });
        jPanel1.add(cetak2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void tampil_combo()
    {
        try {
        Connection con = Koneksi.getConnection();
        Statement stt = con.createStatement();
        String sql = "select netWeight from informationdata order by netWeight asc";      
        ResultSet res = stt.executeQuery(sql);                               
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
            box1.addItem((String) ob[0]);                                      
        }
        res.close(); stt.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
}
    private void cetakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakBtnActionPerformed
       Connection con = Koneksi.getConnection();
            String NamaFile = "/CetakData/report1.jasper";
            HashMap hash = new HashMap();
        try {
            hash.put("angka", noPacking.getText());
            hash.put("Type", box1.getSelectedItem().toString());
            runReportDefault(NamaFile,hash);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cetakBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpanData sm = new SimpanData();
        this.setVisible(false);
        sm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void noPackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPackingActionPerformed

    }//GEN-LAST:event_noPackingActionPerformed

    private void box1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_box1ItemStateChanged

    }//GEN-LAST:event_box1ItemStateChanged

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
      
    }//GEN-LAST:event_box1ActionPerformed

    private void noPackingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noPackingKeyTyped
          char c=evt.getKeyChar();
        if (!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Harus Angka Broh");
        }
    }//GEN-LAST:event_noPackingKeyTyped

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
      System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void cetak2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak2BtnActionPerformed
     Connection con = Koneksi.getConnection();
            String NamaFile = "/CetakData/report2.jasper";
            HashMap hash = new HashMap();
        try {
            hash.put("angka", noPacking.getText());
            hash.put("Type", box1.getSelectedItem().toString());
            runReportDefault(NamaFile,hash);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cetak2BtnActionPerformed

     public void runReportDefault(String sourcefilename, HashMap hash) {
        Connection con = Koneksi.getConnection();
        try {
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
            JasperPrint jprint = JasperFillManager.fillReport(report,hash, con);
            jprint.setPageWidth(595);
            jprint.setPageHeight(421);
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CetakUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CetakUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CetakUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CetakUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CetakUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box1;
    private javax.swing.JButton cetak2Btn;
    private javax.swing.JButton cetakBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField noPacking;
    // End of variables declaration//GEN-END:variables
}
